// export this to EditUserInfoForm and map through for the options in select
export const countries = [
  { country: "Afghanistan", abbreviation: "af", phoneCode: "93" },
  { country: "Aland Islands", abbreviation: "ax", phoneCode: "358" },
  { country: "Albania", abbreviation: "al", phoneCode: "355" },
  { country: "Algeria", abbreviation: "dz", phoneCode: "213" },
  { country: "American Samoa", abbreviation: "as", phoneCode: "1684" },
  { country: "Andorra", abbreviation: "ad", phoneCode: "376" },
  { country: "Angola", abbreviation: "ao", phoneCode: "244" },
  { country: "Anguilla", abbreviation: "ai", phoneCode: "1264" },
  { country: "Antarctica", abbreviation: "aq", phoneCode: "672" },
  { country: "Antigua and Barbuda", abbreviation: "ag", phoneCode: "1268" },
  { country: "Argentina", abbreviation: "ar", phoneCode: "54" },
  { country: "Armenia", abbreviation: "am", phoneCode: "374" },
  { country: "Aruba", abbreviation: "aw", phoneCode: "297" },
  { country: "Australia", abbreviation: "au", phoneCode: "61" },
  { country: "Austria", abbreviation: "at", phoneCode: "43" },
  { country: "Azerbaijan", abbreviation: "az", phoneCode: "994" },
  { country: "Bahamas", abbreviation: "bs", phoneCode: "1242" },
  { country: "Bahrain", abbreviation: "bh", phoneCode: "973" },
  { country: "Bangladesh", abbreviation: "bd", phoneCode: "880" },
  { country: "Barbados", abbreviation: "bb", phoneCode: "1246" },
  { country: "Belarus", abbreviation: "by", phoneCode: "375" },
  { country: "Belgium", abbreviation: "be", phoneCode: "32" },
  { country: "Belize", abbreviation: "bz", phoneCode: "501" },
  { country: "Benin", abbreviation: "bj", phoneCode: "229" },
  { country: "Bermuda", abbreviation: "bm", phoneCode: "1441" },
  { country: "Bhutan", abbreviation: "bt", phoneCode: "975" },
  { country: "Bolivia", abbreviation: "bo", phoneCode: "591" },
  { country: "Bonaire, Sint Eustasius and Saba", abbreviation: "bq", phoneCode: "599" },
  { country: "Bosnia and Herzegovina", abbreviation: "ba", phoneCode: "387" },
  { country: "Botswana", abbreviation: "bw", phoneCode: "267" },
  { country: "Bouvet Island", abbreviation: "bv", phoneCode: "55" },
  { country: "Brazil", abbreviation: "br", phoneCode: "55" },
  { country: "British Indian Ocean Territory", abbreviation: "io", phoneCode: "246" },
  { country: "Brunei Darussalam", abbreviation: "bn", phoneCode: "673" },
  { country: "Bulgaria", abbreviation: "bg", phoneCode: "359" },
  { country: "Burkina Faso", abbreviation: "bf", phoneCode: "226" },
  { country: "Burundi", abbreviation: "bi", phoneCode: "257" },
  { country: "Cambodia", abbreviation: "kh", phoneCode: "855" },
  { country: "Cameroon", abbreviation: "cm", phoneCode: "237" },
  { country: "Canada", abbreviation: "ca", phoneCode: "1" },
  { country: "Cape Verde", abbreviation: "cv", phoneCode: "238" },
  { country: "Cayman Islands", abbreviation: "ky", phoneCode: "1345" },
  { country: "Central African Republic", abbreviation: "cf", phoneCode: "236" },
  { country: "Chad", abbreviation: "td", phoneCode: "235" },
  { country: "Chile", abbreviation: "cl", phoneCode: "56" },
  { country: "China", abbreviation: "cn", phoneCode: "86" },
  { country: "Christmas Island", abbreviation: "cx", phoneCode: "61" },
  { country: "Cocos (Keeling) Islands", abbreviation: "cc", phoneCode: "672" },
  { country: "Colombia", abbreviation: "co", phoneCode: "57" },
  { country: "Comoros", abbreviation: "km", phoneCode: "269" },
  { country: "Congo", abbreviation: "cg", phoneCode: "242" },
  { country: "Congo, Democratic Republic of the", abbreviation: "cd", phoneCode: "242" },
  { country: "Cook Islands", abbreviation: "ck", phoneCode: "682" },
  { country: "Costa Rica", abbreviation: "cr", phoneCode: "506" },
  { country: "Cote D'Ivoire", abbreviation: "ci", phoneCode: "225" },
  { country: "Croatia", abbreviation: "hr", phoneCode: "385" },
  { country: "Cuba", abbreviation: "cu", phoneCode: "53" },
  { country: "Curacao", abbreviation: "cw", phoneCode: "599" },
  { country: "Cyprus", abbreviation: "cy", phoneCode: "357" },
  { country: "Czech Republic", abbreviation: "cz", phoneCode: "420" },
  { country: "Denmark", abbreviation: "dk", phoneCode: "45" },
  { country: "Djibouti", abbreviation: "dj", phoneCode: "253" },
  { country: "Dominica", abbreviation: "dm", phoneCode: "1767" },
  { country: "Dominican Republic", abbreviation: "do", phoneCode: "1809" },
  { country: "Ecuador", abbreviation: "ec", phoneCode: "593" },
  { country: "Egypt", abbreviation: "eg", phoneCode: "20" },
  { country: "El Salvador", abbreviation: "sv", phoneCode: "503" },
  { country: "Equatorial Guinea", abbreviation: "gq", phoneCode: "240" },
  { country: "Eritrea", abbreviation: "er", phoneCode: "291" },
  { country: "Estonia", abbreviation: "ee", phoneCode: "372" },
  { country: "Eswatini", abbreviation: "sz", phoneCode: "268" },
  { country: "Ethiopia", abbreviation: "et", phoneCode: "251" },
  { country: "Falkland Islands (Malvinas)", abbreviation: "fk", phoneCode: "500" },
  { country: "Faroe Islands", abbreviation: "fo", phoneCode: "298" },
  { country: "Fiji", abbreviation: "fj", phoneCode: "679" },
  { country: "Finland", abbreviation: "fi", phoneCode: "358" },
  { country: "France", abbreviation: "fr", phoneCode: "33" },
  { country: "French Guiana", abbreviation: "gf", phoneCode: "594" },
  { country: "French Polynesia", abbreviation: "pf", phoneCode: "689" },
  { country: "French Southern Territories", abbreviation: "tf", phoneCode: "262" },
  { country: "Gabon", abbreviation: "ga", phoneCode: "241" },
  { country: "Gambia", abbreviation: "gm", phoneCode: "220" },
  { country: "Georgia", abbreviation: "ge", phoneCode: "995" },
  { country: "Germany", abbreviation: "de", phoneCode: "49" },
  { country: "Ghana", abbreviation: "gh", phoneCode: "233" },
  { country: "Gibraltar", abbreviation: "gi", phoneCode: "350" },
  { country: "Greece", abbreviation: "gr", phoneCode: "30" },
  { country: "Greenland", abbreviation: "gl", phoneCode: "299" },
  { country: "Grenada", abbreviation: "gd", phoneCode: "1473" },
  { country: "Guadeloupe", abbreviation: "gp", phoneCode: "590" },
  { country: "Guam", abbreviation: "gu", phoneCode: "1671" },
  { country: "Guatemala", abbreviation: "gt", phoneCode: "502" },
  { country: "Guernsey", abbreviation: "gg", phoneCode: "44" },
  { country: "Guinea", abbreviation: "gn", phoneCode: "224" },
  { country: "Guinea-Bissau", abbreviation: "gw", phoneCode: "245" },
  { country: "Guyana", abbreviation: "gy", phoneCode: "592" },
  { country: "Haiti", abbreviation: "ht", phoneCode: "509" },
  { country: "Heard Island & McDonald Islands", abbreviation: "hm", phoneCode: "61" },
  { country: "Holy See (Vatican City)", abbreviation: "va", phoneCode: "39" },
  { country: "Honduras", abbreviation: "hn", phoneCode: "504" },
  { country: "Hong Kong", abbreviation: "hk", phoneCode: "852" },
  { country: "Hungary", abbreviation: "hu", phoneCode: "36" },
  { country: "Iceland", abbreviation: "is", phoneCode: "354" },
  { country: "India", abbreviation: "in", phoneCode: "91" },
  { country: "Indonesia", abbreviation: "id", phoneCode: "62" },
  { country: "Iran, Islamic Republic of", abbreviation: "ir", phoneCode: "98" },
  { country: "Iraq", abbreviation: "iq", phoneCode: "964" },
  { country: "Ireland", abbreviation: "ie", phoneCode: "353" },
  { country: "Isle of Man", abbreviation: "im", phoneCode: "44" },
  { country: "Israel", abbreviation: "il", phoneCode: "972" },
  { country: "Italy", abbreviation: "it", phoneCode: "39" },
  { country: "Jamaica", abbreviation: "jm", phoneCode: "1876" },
  { country: "Japan", abbreviation: "jp", phoneCode: "81" },
  { country: "Jersey", abbreviation: "je", phoneCode: "44" },
  { country: "Jordan", abbreviation: "jo", phoneCode: "962" },
  { country: "Kazakhstan", abbreviation: "kz", phoneCode: "7" },
  { country: "Kenya", abbreviation: "ke", phoneCode: "254" },
  { country: "Kiribati", abbreviation: "ki", phoneCode: "686" },
  {
    country: "Korea, Democratic People's Republic of",
    abbreviation: "kp",
    phoneCode: "850",
  },
  { country: "Korea, Republic of", abbreviation: "kr", phoneCode: "82" },
  { country: "Kosovo", abbreviation: "xk", phoneCode: "381" },
  { country: "Kuwait", abbreviation: "kw", phoneCode: "965" },
  { country: "Kyrgyzstan", abbreviation: "kg", phoneCode: "996" },
  { country: "Laos", abbreviation: "la", phoneCode: "856" },
  { country: "Latvia", abbreviation: "lv", phoneCode: "371" },
  { country: "Lebanon", abbreviation: "lb", phoneCode: "961" },
  { country: "Lesotho", abbreviation: "ls", phoneCode: "266" },
  { country: "Liberia", abbreviation: "lr", phoneCode: "231" },
  { country: "Libyan Arab Jamahiriya", abbreviation: "ly", phoneCode: "218" },
  { country: "Liechtenstein", abbreviation: "li", phoneCode: "423" },
  { country: "Lithuania", abbreviation: "lt", phoneCode: "370" },
  { country: "Luxembourg", abbreviation: "lu", phoneCode: "352" },
  { country: "Macau", abbreviation: "mo", phoneCode: "853" },
  {
    country: "Macedonia, Former Yugoslav Republic of",
    abbreviation: "mk",
    phoneCode: "389",
  },
  { country: "Madagascar", abbreviation: "mg", phoneCode: "261" },
  { country: "Malawi", abbreviation: "mw", phoneCode: "265" },
  { country: "Malaysia", abbreviation: "my", phoneCode: "60" },
  { country: "Mali", abbreviation: "ml", phoneCode: "223" },
  { country: "Malta", abbreviation: "mt", phoneCode: "356" },
  { country: "Marshall Islands", abbreviation: "mh", phoneCode: "692" },
  { country: "Martinique", abbreviation: "mq", phoneCode: "596" },
  { country: "Mauritania", abbreviation: "mr", phoneCode: "222" },
  { country: "Mauritius", abbreviation: "mu", phoneCode: "230" },
  { country: "Mayotte", abbreviation: "yt", phoneCode: "262" },
  { country: "Mexico", abbreviation: "mx", phoneCode: "52" },
  { country: "Micronesia, Federated States of", abbreviation: "fm", phoneCode: "691" },
  { country: "Moldova, Republic of", abbreviation: "md", phoneCode: "373" },
  { country: "Monaco", abbreviation: "mc", phoneCode: "377" },
  { country: "Mongolia", abbreviation: "mn", phoneCode: "976" },
  { country: "Montenegro", abbreviation: "me", phoneCode: "382" },
  { country: "Montserrat", abbreviation: "ms", phoneCode: "1664" },
  { country: "Morocco", abbreviation: "ma", phoneCode: "212" },
  { country: "Mozambique", abbreviation: "mz", phoneCode: "258" },
  { country: "Myanmar", abbreviation: "mm", phoneCode: "65" },
  { country: "Namibia", abbreviation: "na", phoneCode: "264" },
  { country: "Nauru", abbreviation: "nr", phoneCode: "674" },
  { country: "Nepal", abbreviation: "np", phoneCode: "977" },
  { country: "Netherlands", abbreviation: "nl", phoneCode: "31" },
  { country: "Netherlands Antilles", abbreviation: "an", phoneCode: "599" },
  { country: "New Caledonia", abbreviation: "nc", phoneCode: "687" },
  { country: "New Zealand", abbreviation: "nz", phoneCode: "64" },
  { country: "Nicaragua", abbreviation: "ni", phoneCode: "505" },
  { country: "Niger", abbreviation: "ne", phoneCode: "227" },
  { country: "Nigeria", abbreviation: "ng", phoneCode: "234" },
  { country: "Niue", abbreviation: "nu", phoneCode: "683" },
  { country: "Norfolk Island", abbreviation: "nf", phoneCode: "672" },
  { country: "Northern Mariana Islands", abbreviation: "mp", phoneCode: "1670" },
  { country: "Norway", abbreviation: "no", phoneCode: "47" },
  { country: "Oman", abbreviation: "om", phoneCode: "968" },
  { country: "Pakistan", abbreviation: "pk", phoneCode: "92" },
  { country: "Palau", abbreviation: "pw", phoneCode: "680" },
  { country: "State of Palestine", abbreviation: "ps", phoneCode: "970" },
  { country: "Panama", abbreviation: "pa", phoneCode: "507" },
  { country: "Papua New Guinea", abbreviation: "pg", phoneCode: "675" },
  { country: "Paraguay", abbreviation: "py", phoneCode: "595" },
  { country: "Peru", abbreviation: "pe", phoneCode: "51" },
  { country: "Philippines", abbreviation: "ph", phoneCode: "63" },
  { country: "Pitcairn", abbreviation: "pn", phoneCode: "64" },
  { country: "Poland", abbreviation: "pl", phoneCode: "48" },
  { country: "Portugal", abbreviation: "pt", phoneCode: "351" },
  { country: "Puerto Rico", abbreviation: "pr", phoneCode: "1787" },
  { country: "Qatar", abbreviation: "qa", phoneCode: "974" },
  { country: "Réunion", abbreviation: "re", phoneCode: "262" },
  { country: "Romania", abbreviation: "ro", phoneCode: "40" },
  { country: "Russian Federation", abbreviation: "ru", phoneCode: "7" },
  { country: "Rwanda", abbreviation: "rw", phoneCode: "250" },
  { country: "Saint Barthelemy", abbreviation: "bl", phoneCode: "590" },
  { country: "Saint Helena", abbreviation: "sh", phoneCode: "290" },
  { country: "Saint Kitts and Nevis", abbreviation: "kn", phoneCode: "1869" },
  { country: "Saint Lucia", abbreviation: "lc", phoneCode: "1758" },
  { country: "Saint Martin", abbreviation: "mf", phoneCode: "590" },
  { country: "Saint Pierre and Miquelon", abbreviation: "pm", phoneCode: "508" },
  { country: "Saint Vincent and the Grenadines", abbreviation: "vc", phoneCode: "1784" },
  { country: "Samoa", abbreviation: "ws", phoneCode: "684" },
  { country: "San Marino", abbreviation: "sm", phoneCode: "378" },
  { country: "Sao Tome and Principe", abbreviation: "st", phoneCode: "239" },
  { country: "Saudi Arabia", abbreviation: "sa", phoneCode: "966" },
  { country: "Senegal", abbreviation: "sn", phoneCode: "221" },
  { country: "Serbia", abbreviation: "rs", phoneCode: "381" },
  { country: "Seychelles", abbreviation: "sc", phoneCode: "248" },
  { country: "Sierra Leone", abbreviation: "sl", phoneCode: "232" },
  { country: "Singapore", abbreviation: "sg", phoneCode: "65" },
  { country: "Sint Maarten", abbreviation: "sx", phoneCode: "721" },
  { country: "Slovakia", abbreviation: "sk", phoneCode: "421" },
  { country: "Slovenia", abbreviation: "si", phoneCode: "386" },
  { country: "Solomon Islands", abbreviation: "sb", phoneCode: "677" },
  { country: "Somalia", abbreviation: "so", phoneCode: "252" },
  { country: "South Africa", abbreviation: "za", phoneCode: "27" },
  {
    country: "South Georgia and the South Sandwich Islands",
    abbreviation: "gs",
    phoneCode: "500",
  },
  { country: "South Sudan", abbreviation: "ss", phoneCode: "211" },
  { country: "Spain", abbreviation: "es", phoneCode: "34" },
  { country: "Sri Lanka", abbreviation: "lk", phoneCode: "94" },
  { country: "Sudan", abbreviation: "sd", phoneCode: "249" },
  { country: "Suriname", abbreviation: "sr", phoneCode: "597" },
  { country: "Svalbard and Jan Mayen", abbreviation: "sj", phoneCode: "47" },
  { country: "Sweden", abbreviation: "se", phoneCode: "46" },
  { country: "Switzerland", abbreviation: "ch", phoneCode: "41" },
  { country: "Syria", abbreviation: "sy", phoneCode: "963" },
  { country: "Taiwan", abbreviation: "tw", phoneCode: "886" },
  { country: "Tajikistan", abbreviation: "tj", phoneCode: "992" },
  { country: "Tanzania, United Republic of", abbreviation: "tz", phoneCode: "255" },
  { country: "Thailand", abbreviation: "th", phoneCode: "66" },
  { country: "Timor-Leste", abbreviation: "tl", phoneCode: "670" },
  { country: "Togo", abbreviation: "tg", phoneCode: "228" },
  { country: "Tokelau", abbreviation: "tk", phoneCode: "690" },
  { country: "Tonga", abbreviation: "to", phoneCode: "676" },
  { country: "Trinidad and Tobago", abbreviation: "tt", phoneCode: "1868" },
  { country: "Tunisia", abbreviation: "tn", phoneCode: "216" },
  { country: "Türkiye", abbreviation: "tr", phoneCode: "90" },
  { country: "Turkmenistan", abbreviation: "tm", phoneCode: "7370" },
  { country: "Turks and Caicos Islands", abbreviation: "tc", phoneCode: "1649" },
  { country: "Tuvalu", abbreviation: "tv", phoneCode: "688" },
  { country: "Uganda", abbreviation: "ug", phoneCode: "256" },
  { country: "Ukraine", abbreviation: "ua", phoneCode: "380" },
  { country: "United Arab Emirates", abbreviation: "ae", phoneCode: "971" },
  { country: "United Kingdom", abbreviation: "gb", phoneCode: "44" },
  { country: "United States", abbreviation: "us", phoneCode: "1" },
  { country: "United States Minor Outlying Islands", abbreviation: "um", phoneCode: "1" },
  { country: "Uruguay", abbreviation: "uy", phoneCode: "598" },
  { country: "Uzbekistan", abbreviation: "uz", phoneCode: "998" },
  { country: "Vanuatu", abbreviation: "vu", phoneCode: "678" },
  { country: "Venezuela", abbreviation: "ve", phoneCode: "58" },
  { country: "Vietnam", abbreviation: "vn", phoneCode: "84" },
  { country: "Virgin Islands, British", abbreviation: "vg", phoneCode: "1284" },
  { country: "Virgin Islands, U.S.", abbreviation: "vi", phoneCode: "1340" },
  { country: "Wallis and Futuna", abbreviation: "wf", phoneCode: "681" },
  { country: "Western Sahara", abbreviation: "eh", phoneCode: "212" },
  { country: "Yemen", abbreviation: "ye", phoneCode: "967" },
  { country: "Zambia", abbreviation: "zm", phoneCode: "260" },
  { country: "Zimbabwe", abbreviation: "zw", phoneCode: "263" },
];

const countryPhoneCodesWithNumbers3To8DigitsLong = ["974"];

const countryPhoneCodesWithNumbers3To9DigitsLong = ["355"];

const countryPhoneCodesWithNumbers3To10DigitsLong = ["64"];

const countryPhoneCodesWithNumbers4DigitsLong = ["683", "690"];

const countryPhoneCodesWithNumbers4To7DigitsLong = ["674"];

const countryPhoneCodesWithNumbers4To9DigitsLong = ["852", "421", "352"];

const countryPhoneCodesWithNumbers4To11DigitsLong = ["675", "598", "352"];

const countryPhoneCodesWithNumbers4To12DigitsLong = ["420", "41", "381", "382"];

const countryPhoneCodesWithNumbers4To13DigitsLong = ["43"];

const countryPhoneCodesWithNumbers5DigitsLong = ["686", "677", "682", "500"];

const countryPhoneCodesWithNumbers5To6DigitsLong = ["688"];

const countryPhoneCodesWithNumbers5To7DigitsLong = ["678", "676"];

const countryPhoneCodesWithNumbers5To8DigitsLong = ["47", "252"];

const countryPhoneCodesWithNumbers5To9DigitsLong = ["377", "595", "962", "233", "243"];

const countryPhoneCodesWithNumbers5To10DigitsLong = ["62", "263"];

const countryPhoneCodesWithNumbers5To12DigitsLong = ["358"];

const countryPhoneCodesWithNumbers5To13DigitsLong = ["81"];

const countryPhoneCodesWithNumbers5To15DigitsLong = ["61"];

const countryPhoneCodesWithNumbers6DigitsLong = [
  "681",
  "508",
  "298",
  "299",
  "687",
  "689",
  "253",
];

const countryPhoneCodesWithNumbers6To7DigitsLong = ["597", "241"];

const countryPhoneCodesWithNumbers6To8DigitsLong = ["53"];

const countryPhoneCodesWithNumbers6To9DigitsLong = ["376", "967", "48"];

const countryPhoneCodesWithNumbers6To10DigitsLong = ["880", "98", "254", "264", "378"];

const countryPhoneCodesWithNumbers6To13DigitsLong = ["49"];

const countryPhoneCodesWithNumbers6To17DigitsLong = ["850"];

const countryPhoneCodesWithNumbers7DigitsLong = [
  "680",
  "692",
  "297",
  "248",
  "691",
  "239",
  "501",
  "673",
  "960",
  "238",
  "592",
  "269",
  "679",
  "230",
  "220",
  "291",
  "222",
];

const countryPhoneCodesWithNumbers7To8DigitsLong = [
  "599",
  "853",
  "975",
  "268",
  "371",
  "267",
  "976",
  "965",
  "507",
  "968",
  "961",
  "231",
  "265",
];

const countryPhoneCodesWithNumbers7To9DigitsLong = [
  "423",
  "354",
  "359",
  "60",
  "95",
  "20",
];

const countryPhoneCodesWithNumbers7To10DigitsLong = ["91", "234", "84", "44", "372"];

const countryPhoneCodesWithNumbers7To11DigitsLong = ["353", "503"];

const countryPhoneCodesWithNumbers7To13DigitsLong = ["46"];

const countryPhoneCodesWithNumbers8DigitsLong = [
  "350",
  "356",
  "973",
  "386",
  "266",
  "370",
  "374",
  "387",
  "373",
  "506",
  "236",
  "45",
  "993",
  "505",
  "232",
  "228",
  "504",
  "509",
  "216",
  "591",
  "257",
  "229",
  "224",
  "855",
  "502",
  "593",
  "235",
  "223",
  "226",
  "227",
  "237",
  "225",
];

const countryPhoneCodesWithNumbers8To9DigitsLong = [
  "218",
  "972",
  "971",
  "36",
  "994",
  "32",
  "56",
  "886",
  "977",
  "258",
  "966",
  "213",
  "66",
];

const countryPhoneCodesWithNumbers8To10DigitsLong = ["63", "57", "964", "856", "963"];

const countryPhoneCodesWithNumbers8To11DigitsLong = ["357", "51", "82", "92"];

const countryPhoneCodesWithNumbers8To12DigitsLong = ["385", "65"];

const countryPhoneCodesWithNumbers9DigitsLong = [
  "594",
  "596",
  "590",
  "995",
  "996",
  "992",
  "250",
  "31",
  "221",
  "40",
  "260",
  "94",
  "998",
  "244",
  "380",
  "212",
  "93",
  "34",
  "249",
  "256",
  "27",
  "33",
  "255",
  "251",
];

const countryPhoneCodesWithNumbers9To10DigitsLong = ["261", "375"];

const countryPhoneCodesWithNumbers9To11DigitsLong = ["351", "86"];

const countryPhoneCodesWithNumbers10DigitsLong = [
  "58",
  "7",
  "30",
  "1",
  "54",
  "90",
  "52",
  "55",
];

const countryPhoneCodesUpTo11DigitsLong = ["39"];

export const phoneNumberLengthRanges = {
  countryPhoneCodesWithNumbers3To8DigitsLong,
  countryPhoneCodesWithNumbers3To9DigitsLong,
  countryPhoneCodesWithNumbers3To10DigitsLong,
  countryPhoneCodesWithNumbers4DigitsLong,
  countryPhoneCodesWithNumbers4To7DigitsLong,
  countryPhoneCodesWithNumbers4To9DigitsLong,
  countryPhoneCodesWithNumbers4To11DigitsLong,
  countryPhoneCodesWithNumbers4To12DigitsLong,
  countryPhoneCodesWithNumbers4To13DigitsLong,
  countryPhoneCodesWithNumbers5DigitsLong,
  countryPhoneCodesWithNumbers5To6DigitsLong,
  countryPhoneCodesWithNumbers5To7DigitsLong,
  countryPhoneCodesWithNumbers5To8DigitsLong,
  countryPhoneCodesWithNumbers5To9DigitsLong,
  countryPhoneCodesWithNumbers5To10DigitsLong,
  countryPhoneCodesWithNumbers5To12DigitsLong,
  countryPhoneCodesWithNumbers5To13DigitsLong,
  countryPhoneCodesWithNumbers5To15DigitsLong,
  countryPhoneCodesWithNumbers6DigitsLong,
  countryPhoneCodesWithNumbers6To7DigitsLong,
  countryPhoneCodesWithNumbers6To8DigitsLong,
  countryPhoneCodesWithNumbers6To9DigitsLong,
  countryPhoneCodesWithNumbers6To10DigitsLong,
  countryPhoneCodesWithNumbers6To13DigitsLong,
  countryPhoneCodesWithNumbers6To17DigitsLong,
  countryPhoneCodesWithNumbers7DigitsLong,
  countryPhoneCodesWithNumbers7To8DigitsLong,
  countryPhoneCodesWithNumbers7To9DigitsLong,
  countryPhoneCodesWithNumbers7To10DigitsLong,
  countryPhoneCodesWithNumbers7To11DigitsLong,
  countryPhoneCodesWithNumbers7To13DigitsLong,
  countryPhoneCodesWithNumbers8DigitsLong,
  countryPhoneCodesWithNumbers8To9DigitsLong,
  countryPhoneCodesWithNumbers8To10DigitsLong,
  countryPhoneCodesWithNumbers8To11DigitsLong,
  countryPhoneCodesWithNumbers8To12DigitsLong,
  countryPhoneCodesWithNumbers9DigitsLong,
  countryPhoneCodesWithNumbers9To10DigitsLong,
  countryPhoneCodesWithNumbers9To11DigitsLong,
  countryPhoneCodesWithNumbers10DigitsLong,
  countryPhoneCodesUpTo11DigitsLong,
};
