// export this to EditUserInfoForm and map through for the options in select
export const countriesAndTheirPhoneCodes = [
  { country: "Afghanistan", phoneCode: "93" },
  { country: "Aland Islands", phoneCode: "358" },
  { country: "Albania", phoneCode: "355" },
  { country: "Algeria", phoneCode: "213" },
  { country: "American Samoa", phoneCode: "1684" },
  { country: "Andorra", phoneCode: "376" },
  { country: "Angola", phoneCode: "244" },
  { country: "Anguilla", phoneCode: "1264" },
  { country: "Antarctica", phoneCode: "672" },
  { country: "Antigua and Barbuda", phoneCode: "1268" },
  { country: "Argentina", phoneCode: "54" },
  { country: "Armenia", phoneCode: "374" },
  { country: "Aruba", phoneCode: "297" },
  { country: "Australia", phoneCode: "61" },
  { country: "Austria", phoneCode: "43" },
  { country: "Azerbaijan", phoneCode: "994" },
  { country: "Bahamas", phoneCode: "1242" },
  { country: "Bahrain", phoneCode: "973" },
  { country: "Bangladesh", phoneCode: "880" },
  { country: "Barbados", phoneCode: "1246" },
  { country: "Belarus", phoneCode: "375" },
  { country: "Belgium", phoneCode: "32" },
  { country: "Belize", phoneCode: "501" },
  { country: "Benin", phoneCode: "229" },
  { country: "Bermuda", phoneCode: "1441" },
  { country: "Bhutan", phoneCode: "975" },
  { country: "Bolivia", phoneCode: "591" },
  { country: "Bonaire, Sint Eustasius and Saba", phoneCode: "599" },
  { country: "Bosnia and Herzegovina", phoneCode: "387" },
  { country: "Botswana", phoneCode: "267" },
  { country: "Bouvet Island", phoneCode: "55" },
  { country: "Brazil", phoneCode: "55" },
  { country: "British Indian Ocean Territory", phoneCode: "246" },
  { country: "Brunei Darussalam", phoneCode: "673" },
  { country: "Bulgaria", phoneCode: "359" },
  { country: "Burkina Faso", phoneCode: "226" },
  { country: "Burundi", phoneCode: "257" },
  { country: "Cambodia", phoneCode: "855" },
  { country: "Cameroon", phoneCode: "237" },
  { country: "Canada", phoneCode: "1" },
  { country: "Cape Verde", phoneCode: "238" },
  { country: "Cayman Islands", phoneCode: "1345" },
  { country: "Central African Republic", phoneCode: "236" },
  { country: "Chad", phoneCode: "235" },
  { country: "Chile", phoneCode: "56" },
  { country: "China", phoneCode: "86" },
  { country: "Christmas Island", phoneCode: "61" },
  { country: "Cocos (Keeling) Islands", phoneCode: "672" },
  { country: "Colombia", phoneCode: "57" },
  { country: "Comoros", phoneCode: "269" },
  { country: "Congo", phoneCode: "242" },
  { country: "Congo, Democratic Republic of the", phoneCode: "242" },
  { country: "Cook Islands", phoneCode: "682" },
  { country: "Costa Rica", phoneCode: "506" },
  { country: "Cote D'Ivoire", phoneCode: "225" },
  { country: "Croatia", phoneCode: "385" },
  { country: "Cuba", phoneCode: "53" },
  { country: "Curacao", phoneCode: "599" },
  { country: "Cyprus", phoneCode: "357" },
  { country: "Czech Republic", phoneCode: "420" },
  { country: "Denmark", phoneCode: "45" },
  { country: "Djibouti", phoneCode: "253" },
  { country: "Dominica", phoneCode: "1767" },
  { country: "Dominican Republic", phoneCode: "1809" },
  { country: "Ecuador", phoneCode: "593" },
  { country: "Egypt", phoneCode: "20" },
  { country: "El Salvador", phoneCode: "503" },
  { country: "Equatorial Guinea", phoneCode: "240" },
  { country: "Eritrea", phoneCode: "291" },
  { country: "Estonia", phoneCode: "372" },
  { country: "Ethiopia", phoneCode: "251" },
  { country: "Falkland Islands (Malvinas)", phoneCode: "500" },
  { country: "Faroe Islands", phoneCode: "298" },
  { country: "Fiji", phoneCode: "679" },
  { country: "Finland", phoneCode: "358" },
  { country: "France", phoneCode: "33" },
  { country: "French Guiana", phoneCode: "594" },
  { country: "French Polynesia", phoneCode: "689" },
  { country: "French Southern Territories", phoneCode: "262" },
  { country: "Gabon", phoneCode: "241" },
  { country: "Gambia", phoneCode: "220" },
  { country: "Georgia", phoneCode: "995" },
  { country: "Germany", phoneCode: "49" },
  { country: "Ghana", phoneCode: "233" },
  { country: "Gibraltar", phoneCode: "350" },
  { country: "Greece", phoneCode: "30" },
  { country: "Greenland", phoneCode: "299" },
  { country: "Grenada", phoneCode: "1473" },
  { country: "Guadeloupe", phoneCode: "590" },
  { country: "Guam", phoneCode: "1671" },
  { country: "Guatemala", phoneCode: "502" },
  { country: "Guernsey", phoneCode: "44" },
  { country: "Guinea", phoneCode: "224" },
  { country: "Guinea-Bissau", phoneCode: "245" },
  { country: "Guyana", phoneCode: "592" },
  { country: "Haiti", phoneCode: "509" },
  { country: "Holy See (Vatican City)", phoneCode: "39" },
  { country: "Honduras", phoneCode: "504" },
  { country: "Hong Kong", phoneCode: "852" },
  { country: "Hungary", phoneCode: "36" },
  { country: "Iceland", phoneCode: "354" },
  { country: "India", phoneCode: "91" },
  { country: "Indonesia", phoneCode: "62" },
  { country: "Iran, Islamic Republic of", phoneCode: "98" },
  { country: "Iraq", phoneCode: "964" },
  { country: "Ireland", phoneCode: "353" },
  { country: "Isle of Man", phoneCode: "44" },
  { country: "Israel", phoneCode: "972" },
  { country: "Italy", phoneCode: "39" },
  { country: "Jamaica", phoneCode: "1876" },
  { country: "Japan", phoneCode: "81" },
  { country: "Jersey", phoneCode: "44" },
  { country: "Jordan", phoneCode: "962" },
  { country: "Kazakhstan", phoneCode: "7" },
  { country: "Kenya", phoneCode: "254" },
  { country: "Kiribati", phoneCode: "686" },
  { country: "Korea, Democratic People's Republic of", phoneCode: "850" },
  { country: "Korea, Republic of", phoneCode: "82" },
  { country: "Kosovo", phoneCode: "381" },
  { country: "Kuwait", phoneCode: "965" },
  { country: "Kyrgyzstan", phoneCode: "996" },
  { country: "Laos", phoneCode: "856" },
  { country: "Latvia", phoneCode: "371" },
  { country: "Lebanon", phoneCode: "961" },
  { country: "Lesotho", phoneCode: "266" },
  { country: "Liberia", phoneCode: "231" },
  { country: "Libyan Arab Jamahiriya", phoneCode: "218" },
  { country: "Liechtenstein", phoneCode: "423" },
  { country: "Lithuania", phoneCode: "370" },
  { country: "Luxembourg", phoneCode: "352" },
  { country: "Macao", phoneCode: "853" },
  { country: "Macedonia, Former Yugoslav Republic of", phoneCode: "389" },
  { country: "Madagascar", phoneCode: "261" },
  { country: "Malawi", phoneCode: "265" },
  { country: "Malaysia", phoneCode: "60" },
  { country: "Mali", phoneCode: "223" },
  { country: "Malta", phoneCode: "356" },
  { country: "Marshall Islands", phoneCode: "692" },
  { country: "Martinique", phoneCode: "596" },
  { country: "Mauritania", phoneCode: "222" },
  { country: "Mauritius", phoneCode: "230" },
  { country: "Mayotte", phoneCode: "262" },
  { country: "Mexico", phoneCode: "52" },
  { country: "Micronesia, Federated States of", phoneCode: "691" },
  { country: "Moldova, Republic of", phoneCode: "373" },
  { country: "Monaco", phoneCode: "377" },
  { country: "Mongolia", phoneCode: "976" },
  { country: "Montenegro", phoneCode: "382" },
  { country: "Montserrat", phoneCode: "1664" },
  { country: "Morocco", phoneCode: "212" },
  { country: "Mozambique", phoneCode: "258" },
  { country: "Myanmar", phoneCode: "65" },
  { country: "Namibia", phoneCode: "264" },
  { country: "Nauru", phoneCode: "674" },
  { country: "Nepal", phoneCode: "977" },
  { country: "Netherlands", phoneCode: "31" },
  { country: "Netherlands Antilles", phoneCode: "599" },
  { country: "New Caledonia", phoneCode: "687" },
  { country: "New Zealand", phoneCode: "64" },
  { country: "Nicaragua", phoneCode: "505" },
  { country: "Niger", phoneCode: "227" },
  { country: "Nigeria", phoneCode: "234" },
  { country: "Niue", phoneCode: "683" },
  { country: "Norfolk Island", phoneCode: "672" },
  { country: "Northern Mariana Islands", phoneCode: "1670" },
  { country: "Norway", phoneCode: "47" },
  { country: "Oman", phoneCode: "968" },
  { country: "Pakistan", phoneCode: "92" },
  { country: "Palau", phoneCode: "680" },
  { country: "Palestinian Territory, Occupied", phoneCode: "970" },
  { country: "Panama", phoneCode: "507" },
  { country: "Papua New Guinea", phoneCode: "675" },
  { country: "Paraguay", phoneCode: "595" },
  { country: "Peru", phoneCode: "51" },
  { country: "Philippines", phoneCode: "63" },
  { country: "Pitcairn", phoneCode: "64" },
  { country: "Poland", phoneCode: "48" },
  { country: "Portugal", phoneCode: "351" },
  { country: "Puerto Rico", phoneCode: "1787" },
  { country: "Qatar", phoneCode: "974" },
  { country: "Reunion", phoneCode: "262" },
  { country: "Romania", phoneCode: "40" },
  { country: "Russian Federation", phoneCode: "7" },
  { country: "Rwanda", phoneCode: "250" },
  { country: "Saint Barthelemy", phoneCode: "590" },
  { country: "Saint Helena", phoneCode: "290" },
  { country: "Saint Kitts and Nevis", phoneCode: "1869" },
  { country: "Saint Lucia", phoneCode: "1758" },
  { country: "Saint Martin", phoneCode: "590" },
  { country: "Saint Pierre and Miquelon", phoneCode: "508" },
  { country: "Saint Vincent and the Grenadines", phoneCode: "1784" },
  { country: "Samoa", phoneCode: "684" },
  { country: "San Marino", phoneCode: "378" },
  { country: "Sao Tome and Principe", phoneCode: "239" },
  { country: "Saudi Arabia", phoneCode: "966" },
  { country: "Senegal", phoneCode: "221" },
  { country: "Serbia", phoneCode: "381" },
  { country: "Seychelles", phoneCode: "248" },
  { country: "Sierra Leone", phoneCode: "232" },
  { country: "Singapore", phoneCode: "65" },
  { country: "Sint Maarten", phoneCode: "721" },
  { country: "Slovakia", phoneCode: "421" },
  { country: "Slovenia", phoneCode: "386" },
  { country: "Solomon Islands", phoneCode: "677" },
  { country: "Somalia", phoneCode: "252" },
  { country: "South Africa", phoneCode: "27" },
  { country: "South Georgia and the South Sandwich Islands", phoneCode: "500" },
  { country: "South Sudan", phoneCode: "211" },
  { country: "Spain", phoneCode: "34" },
  { country: "Sri Lanka", phoneCode: "94" },
  { country: "Sudan", phoneCode: "249" },
  { country: "Suriname", phoneCode: "597" },
  { country: "Svalbard and Jan Mayen", phoneCode: "47" },
  { country: "Swaziland", phoneCode: "268" },
  { country: "Sweden", phoneCode: "46" },
  { country: "Switzerland", phoneCode: "41" },
  { country: "Syrian Arab Republic", phoneCode: "963" },
  { country: "Taiwan", phoneCode: "886" },
  { country: "Tajikistan", phoneCode: "992" },
  { country: "Tanzania, United Republic of", phoneCode: "255" },
  { country: "Thailand", phoneCode: "66" },
  { country: "Timor-Leste", phoneCode: "670" },
  { country: "Togo", phoneCode: "228" },
  { country: "Tokelau", phoneCode: "690" },
  { country: "Tonga", phoneCode: "676" },
  { country: "Trinidad and Tobago", phoneCode: "1868" },
  { country: "Tunisia", phoneCode: "216" },
  { country: "Turkey", phoneCode: "90" },
  { country: "Turkmenistan", phoneCode: "7370" },
  { country: "Turks and Caicos Islands", phoneCode: "1649" },
  { country: "Tuvalu", phoneCode: "688" },
  { country: "Uganda", phoneCode: "256" },
  { country: "Ukraine", phoneCode: "380" },
  { country: "United Arab Emirates", phoneCode: "971" },
  { country: "United Kingdom", phoneCode: "44" },
  { country: "United States", phoneCode: "1" },
  { country: "United States Minor Outlying Islands", phoneCode: "1" },
  { country: "Uruguay", phoneCode: "598" },
  { country: "Uzbekistan", phoneCode: "998" },
  { country: "Vanuatu", phoneCode: "678" },
  { country: "Venezuela", phoneCode: "58" },
  { country: "Vietnam", phoneCode: "84" },
  { country: "Virgin Islands, British", phoneCode: "1284" },
  { country: "Virgin Islands, U.S.", phoneCode: "1340" },
  { country: "Wallis and Futuna", phoneCode: "681" },
  { country: "Western Sahara", phoneCode: "212" },
  { country: "Yemen", phoneCode: "967" },
  { country: "Zambia", phoneCode: "260" },
  { country: "Zimbabwe", phoneCode: "263" },
];

const countryPhoneCodesWithNumbers3To8DigitsLong = ["974"];

const countryPhoneCodesWithNumbers3To9DigitsLong = ["355"];

const countryPhoneCodesWithNumbers3To10DigitsLong = ["64"];

const countryPhoneCodesWithNumbers4DigitsLong = ["683", "690"];

const countryPhoneCodesWithNumbers4To7DigitsLong = ["674"];

const countryPhoneCodesWithNumbers4To9DigitsLong = ["852", "421", "352"];

const countryPhoneCodesWithNumbers4To11DigitsLong = ["675", "598", "352"];

const countryPhoneCodesWithNumbers4To12DigitsLong = ["420", "41", "381", "382"];

const countryPhoneCodesWithNumbers4To13DigitsLong = ["43"];

const countryPhoneCodesWithNumbers5DigitsLong = ["686", "677", "682", "500"];

const countryPhoneCodesWithNumbers5To6DigitsLong = ["688"];

const countryPhoneCodesWithNumbers5To7DigitsLong = ["678", "676"];

const countryPhoneCodesWithNumbers5To8DigitsLong = ["47", "252"];

const countryPhoneCodesWithNumbers5To9DigitsLong = ["377", "595", "962", "233", "243"];

const countryPhoneCodesWithNumbers5To10DigitsLong = ["62", "263"];

const countryPhoneCodesWithNumbers5To12DigitsLong = ["358"];

const countryPhoneCodesWithNumbers5To13DigitsLong = ["81"];

const countryPhoneCodesWithNumbers5To15DigitsLong = ["61"];

const countryPhoneCodesWithNumbers6DigitsLong = [
  "681",
  "508",
  "298",
  "299",
  "687",
  "689",
  "253",
];

const countryPhoneCodesWithNumbers6To7DigitsLong = ["597", "241"];

const countryPhoneCodesWithNumbers6To8DigitsLong = ["53"];

const countryPhoneCodesWithNumbers6To9DigitsLong = ["376", "967", "48"];

const countryPhoneCodesWithNumbers6To10DigitsLong = ["880", "98", "254", "264", "378"];

const countryPhoneCodesWithNumbers6To13DigitsLong = ["49"];

const countryPhoneCodesWithNumbers6To17DigitsLong = ["850"];

const countryPhoneCodesWithNumbers7DigitsLong = [
  "680",
  "692",
  "297",
  "248",
  "691",
  "239",
  "501",
  "673",
  "960",
  "238",
  "592",
  "269",
  "679",
  "230",
  "220",
  "291",
  "222",
];

const countryPhoneCodesWithNumbers7To8DigitsLong = [
  "599",
  "853",
  "975",
  "268",
  "371",
  "267",
  "976",
  "965",
  "507",
  "968",
  "961",
  "231",
  "265",
];

const countryPhoneCodesWithNumbers7To9DigitsLong = [
  "423",
  "354",
  "359",
  "60",
  "95",
  "20",
];

const countryPhoneCodesWithNumbers7To10DigitsLong = ["91", "234", "84", "44", "372"];

const countryPhoneCodesWithNumbers7To11DigitsLong = ["353", "503"];

const countryPhoneCodesWithNumbers7To13DigitsLong = ["46"];

const countryPhoneCodesWithNumbers8DigitsLong = [
  "350",
  "356",
  "973",
  "386",
  "266",
  "370",
  "374",
  "387",
  "373",
  "506",
  "236",
  "45",
  "993",
  "505",
  "232",
  "228",
  "504",
  "509",
  "216",
  "591",
  "257",
  "229",
  "224",
  "855",
  "502",
  "593",
  "235",
  "223",
  "226",
  "227",
  "237",
  "225",
];

const countryPhoneCodesWithNumbers8To9DigitsLong = [
  "218",
  "972",
  "971",
  "36",
  "994",
  "32",
  "56",
  "886",
  "977",
  "258",
  "966",
  "213",
  "66",
];

const countryPhoneCodesWithNumbers8To10DigitsLong = ["63", "57", "964", "856", "963"];

const countryPhoneCodesWithNumbers8To11DigitsLong = ["357", "51", "82", "92"];

const countryPhoneCodesWithNumbers8To12DigitsLong = ["385", "65"];

const countryPhoneCodesWithNumbers9DigitsLong = [
  "594",
  "596",
  "590",
  "995",
  "996",
  "992",
  "250",
  "31",
  "221",
  "40",
  "260",
  "94",
  "998",
  "244",
  "380",
  "212",
  "93",
  "34",
  "249",
  "256",
  "27",
  "33",
  "255",
  "251",
];

const countryPhoneCodesWithNumbers9To10DigitsLong = ["261", "375"];

const countryPhoneCodesWithNumbers9To11DigitsLong = ["351", "86"];

const countryPhoneCodesWithNumbers10DigitsLong = [
  "58",
  "7",
  "30",
  "1",
  "54",
  "90",
  "52",
  "55",
];

const countryPhoneCodesUpTo11DigitsLong = ["39"];

export const phoneNumberLengthRanges = {
  countryPhoneCodesWithNumbers3To8DigitsLong,
  countryPhoneCodesWithNumbers3To9DigitsLong,
  countryPhoneCodesWithNumbers3To10DigitsLong,
  countryPhoneCodesWithNumbers4DigitsLong,
  countryPhoneCodesWithNumbers4To7DigitsLong,
  countryPhoneCodesWithNumbers4To9DigitsLong,
  countryPhoneCodesWithNumbers4To11DigitsLong,
  countryPhoneCodesWithNumbers4To12DigitsLong,
  countryPhoneCodesWithNumbers4To13DigitsLong,
  countryPhoneCodesWithNumbers5DigitsLong,
  countryPhoneCodesWithNumbers5To6DigitsLong,
  countryPhoneCodesWithNumbers5To7DigitsLong,
  countryPhoneCodesWithNumbers5To8DigitsLong,
  countryPhoneCodesWithNumbers5To9DigitsLong,
  countryPhoneCodesWithNumbers5To10DigitsLong,
  countryPhoneCodesWithNumbers5To12DigitsLong,
  countryPhoneCodesWithNumbers5To13DigitsLong,
  countryPhoneCodesWithNumbers5To15DigitsLong,
  countryPhoneCodesWithNumbers6DigitsLong,
  countryPhoneCodesWithNumbers6To7DigitsLong,
  countryPhoneCodesWithNumbers6To8DigitsLong,
  countryPhoneCodesWithNumbers6To9DigitsLong,
  countryPhoneCodesWithNumbers6To10DigitsLong,
  countryPhoneCodesWithNumbers6To13DigitsLong,
  countryPhoneCodesWithNumbers6To17DigitsLong,
  countryPhoneCodesWithNumbers7DigitsLong,
  countryPhoneCodesWithNumbers7To8DigitsLong,
  countryPhoneCodesWithNumbers7To9DigitsLong,
  countryPhoneCodesWithNumbers7To10DigitsLong,
  countryPhoneCodesWithNumbers7To11DigitsLong,
  countryPhoneCodesWithNumbers7To13DigitsLong,
  countryPhoneCodesWithNumbers8DigitsLong,
  countryPhoneCodesWithNumbers8To9DigitsLong,
  countryPhoneCodesWithNumbers8To10DigitsLong,
  countryPhoneCodesWithNumbers8To11DigitsLong,
  countryPhoneCodesWithNumbers8To12DigitsLong,
  countryPhoneCodesWithNumbers9DigitsLong,
  countryPhoneCodesWithNumbers9To10DigitsLong,
  countryPhoneCodesWithNumbers9To11DigitsLong,
  countryPhoneCodesWithNumbers10DigitsLong,
  countryPhoneCodesUpTo11DigitsLong,
};
